### ISSUE TITLE
S3 Guides

### ISSUE THREAD

**Issue by duyleekun** [spree/spree-guides#254]
Which is the correct way to config s3 for spree 3.0?

https://github.com/spree/spree-guides/blob/master/content/developer/core/preferences.md#s3-support
https://github.com/spree/spree-guides/blob/master/content/developer/deployment/heroku.md#s3-support
https://github.com/spree/spree-guides/blob/master/content/user/config/configuring_images.md
https://guides.spreecommerce.com/developer/s3_storage.html
https://guides.spreecommerce.com/release_notes/spree_2_2_0.html

I've tested `https://guides.spreecommerce.com/developer/s3_storage.html` without luck. It uploads directly to public/spree directory

The release_notes help though, it worked for me now :+1:

**Comment by JDutil** [comment]
The https://guides.spreecommerce.com/developer/s3_storage.html should be correct. FYI the guides documentation is now in this repo https://github.com/spree/spree/tree/master/guides so spree/spree-guides is out of date.
