### ISSUE TITLE
HTTPS not working on guides.spreecommerce.com

### ISSUE THREAD

**Issue by henwen** [spree/spree-guides#258]
Pages on guides.spreecommerce.com currently can't be loaded via HTTPS, only HTTP. Any HTTPS requests timeout.

Maybe someone just needs to update the SSL certificate?

**Comment by schof** [comment]
We're aware of the issue.  Unfortunately the ops people needed to handle this are on spring break and it's not such an emergency to risk a change without them.  Scheduled to be fixed next week.
