### ISSUE TITLE
Document Option Types + Option Values APIs

### ISSUE THREAD

**Issue by radar** [spree/spree-guides#99]
There is no documentation for these endpoints in the API.

**Comment by Qwertie-** [comment]
Wow, old issue report. I just run into this issue. I'll take a look through the code and see if I can come up with some documentation later.

**Comment by Qwertie-** [comment]
@damianlegawiec why close the issue? I couldn't find a doc page for creating option types using the api. or maybe its somewhere else I didn't see?

**Comment by damianlegawiec** [comment]
@Qwertie- this repo is outdated, all of the guides were moved to https://github.com/spree/spree
